### PR TITLE
Speech to text

### PR DESCRIPTION
**Pull request by TomasArguello**
This branch added the Speech-To-Text asset (https://github.com/oshoham/UnityGoogleStreamingSpeechToText) to the project. In the Installation scene, a single game object named "Speech-To-Text Manager" was added. This manager can be used to test if the asset works. The most important thing that must be included is the gcp_credentials.json file, which needs to be added to the Assets/StreamingAssets folder. I will create a document on how to create a service account in order to use this Asset with the project.

### CODE REVIEW

**Comment by jalberse** [comment]
Checking out this PR results in the following errors. This is after deleting and re-building the Library folder, which resolved another error message (which is something Unity can sometimes have problems with I think, needing to rebuild that folder). These are still present:

- Asset Packages/com.oshoham.unity-google-cloud-streaming-speech-to-text/LICENSE.md has no meta file, but it's in an immutable folder. The asset will be ignored.
- Asset Packages/com.oshoham.unity-google-cloud-streaming-speech-to-text/LICENSE.md has no meta file, but it's in an immutable folder. The asset will be ignored.
- Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included on the current platform. Only one assembly with the same name is allowed per platform. (D:/projects/Creatures/Library/PackageCache/com.unity.nuget.newtonsoft-json@3.0.2/Runtime/Newtonsoft.Json.dll)
- Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included on the current platform. Only one assembly with the same name is allowed per platform. (D:/projects/Creatures/Library/PackageCache/com.oshoham.unity-google-cloud-streaming-speech-to-text@0.1.8/Plugins/Newtonsoft.Json.dll)
- Asset Packages/com.oshoham.unity-google-cloud-streaming-speech-to-text/LICENSE.md has no meta file, but it's in an immutable folder. The asset will be ignored.

@TomasArguello Did you get these errors while working on this change? I don't want to merge something which will break on a fresh check-out.

For the duplicate dlls, I think you can:

- re-import one of the dependencies, but un-check the Newtonsoft.Json.dll file so it doesn't get imported. Unity will use the other one.
- If that doesn't work, Newtonsoft.Json.dll might be included with Unity now. If that's the case, we should re-import both packages, but uncheck Newtonsoft.Json.dll from both of them so that we don't import it at all, and Unity will just use the one it comes with.

The LICENSE.md files being ignored probably doesn't break anything since they're not assets, but I also don't want this error message to occur when checking out the project. So, we probably want to uncheck the LICENSE.md on package import as well, so that we don't import it under Assets/. We still want to include the licenses though, so we should add them under a new Licenses/ folder at the top of the project.

Once those changes are in, I think the error messages will be resolved.

**Comment by TomasArguello** [comment]
Yo! I had deleted the Newtonsoft.Json.dll file because it had been giving me errors when I first installed the Speech-To-Text package. So, when you recreated the Library folder it re-added that file. I can remove the package, push that change to the branch and then re-add the package. Once I re-add the package, I can push the change again without including the LICENSE.md file but if you rebuild the Library folder on your end, it'll simply re-add those files. Also, I added this package from OpenUPM (https://openupm.com/packages/com.oshoham.unity-google-cloud-streaming-speech-to-text/), so I can't choose which files to add to the project. What I did to remove the error was simply delete the Unity-Google-Cloud-Streaming-Speech-to-Text version of the Newtonsoft.Json.dll file. Apologies for the inconvenience.

**Comment by jalberse** [comment]
I'm actually developing on a new machine (my laptop), so I was checking out the repository 100% fresh. Since any fresh clone of this repository will have Unity build the Library/ folder, we want to ensure that any build/rebuild of the Library folder will work, rather than requiring any steps to delete files after a Library/ rebuild.

I'll look into fixing that, though. A definitive way to do that is to just re-export the packages from Unity excluding the DLLs and licenses (placing the license files elsewhere), and then re-importing those custom packages that exclude those files. The disadvantage here is potentially more complicated upgrade paths for those packages, but that's not a high priority for us. There's likely other ways to ensure git/Unity respects us wanting to exclude these files as well.

But okay, the issue makes sense to me and with the extra context you've provided about how you solved it, I'll go ahead and resolve it myself and then merge this PR once it's done. I'll likely get to it around Sunday.

**Comment by jalberse** [comment]
I was able to resolve the DLL dependency issue (and in the process, the missing .meta file issue). Fresh clones of the repository, and Library/ rebuilds, should now work without having to make local changes manually.

I describe the change here: https://github.com/jalberse/Creatures/pull/94/commits/08e9cc53e6c4e3b0c769dc57f479d8802ccfc342

I did basically what I described prior, but:

(1) You don't need to re-export packages, you can just copy them from PackageCache/ to Packages/ and Unity will actually update its manifest to use your local version instead of the registry version. This allows for local edits (like deleting the DLL) but means updating is more complex, since you can't just one-click-upgrade from the registry. I did this for the speech-to-text package and deleted its DLL version, which is the accepted solution wherever I saw this issue online.

(2) ... But, I had to disable DLL assembly version checking. This is fine for now, because the Unity DLL (13.0.0.0) is more recent than the version referenced by the speech-to-text project (10.0.0.0, 11.0.0.0), and referencing future versions should be OK. I tried to overwrite Unity's DLL with the external DLL, since it would fix the assembly version check error, but other Unity packages depend on 13.0.0.0 features that would be missing with this method - though theoretically you could move those out to Packages/ as well and edit them to be compatible with earlier versions. You could also edit the speech-to-text project to accept 13.0.0.0 as the DLL version, I think.

I don't love disabling assembly assembly version validation - it means we could miss a bug in some future dependency - but this issue stems from both Unity and 3rd party package developers deciding to include the DLL, unwilling to assume responsibility for conflicts (though for 3rd party developers it's more forgivable, since they could be targeting environments other than Unity where including the DLL makes sense).

**Comment by jalberse** [comment]
@jamsterwes FYI on this issue:

(1) In your local machine, you'll need the JSON file with the credentials for speech-to-text. We don't include in git to avoid private key leak. Tomas can provide the file.
(2) Just be aware that this change disables assembly version validation in the project settings. If you ever add a dependency and get odd errors you can't debug, you can re-enable it and check if there are any issues with mismatched DLLs.

**Pull request merged**
